package com.trackingplan.client.sdk;

import com.trackingplan.client.sdk.interception.HttpRequest;
import com.trackingplan.client.sdk.interception.InterceptionContext;
import com.trackingplan.shared.Storage;

import org.junit.Assert;
import org.junit.Test;

import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * End-to-end instrumented tests for Firebase Analytics (lib-firebase) request processing.
 * Verifies the full Android pipeline: HttpRequest with lib-firebase JSON payload
 * → provider detection → adaptive sampling evaluation → batch with correct sampling_rate.
 */
public class FirebaseInstrumentedTest extends BaseInstrumentedTest {

    @Test
    public void given_AdaptiveSamplingForFirebase_when_PurchaseEventProcessed_then_AdaptiveSamplingApplied() throws Exception {
        // Given - Pre-populate cache with adaptive sampling config for Firebase.
        // The pattern uses the "and" operator with method=logEvent condition, matching
        // the format generated by lib-firebase_parser.get_match_conditions().
        // Using event sample_rate=1 to ensure deterministic rescue probability (1.0)
        // for unsampled sessions, matching the pattern used by the Amplitude test.
        var storage = Storage.Companion.create(TEST_TP_ID, TEST_ENVIRONMENT);
        String configJson = """
            {
                "sample_rate": 100,
                "options": {
                    "useAdaptiveSampling": true,
                    "adaptiveSamplingPatterns": ["{\\"provider\\":\\"lib-firebase\\",\\"match\\":{\\"and\\":[{\\"method\\":\\"logEvent\\"},{\\"name\\":\\"purchase\\"}]},\\"sample_rate\\":1}"]
                }
            }
            """;
        storage.getIngestConfigCache().save(configJson);

        startTrackingplan(TEST_TP_ID, TEST_ENVIRONMENT, false);
        final var instance = TrackingplanInstance.getInstance();

        // When - Process lib-firebase request with a "purchase" logEvent
        logger.reset();
        logger.expectExactMessage("Processing request: code://com.google.firebase.analytics.FirebaseAnalytics");
        logger.expectMessageStartingWithAndContaining("Request queued", List.of("code://com.google.firebase.analytics.FirebaseAnalytics"));
        logger.expectMessageStartingWithAndContaining("Batch:", List.of(
                "\"provider\": \"lib-firebase\"",
                "\"sampling_rate\": 1",
                "\"sampling_mode\": \"ADAPTIVE\\/EVENT_DICE\\/EVENT_MATCHED\""
        ));

        instance.runSync(() -> {
            instance.processRequest(createFakeFirebaseRequest(), createContext());
        });
        instance.flushQueue();
        instance.waitForRunSync();

        // Then
        logger.assertExpectationsMatch();
        Assert.assertFalse(
                "Firebase request should not be ignored as unknown destination",
                logger.containsExactMessage("Request ignored. Doesn't belong to a supported destination")
        );
    }

    // Helpers

    private HttpRequest createFakeFirebaseRequest() {
        // Android SDK v2 payload format: method and name nested inside params
        byte[] payloadBytes = "{\"version\":2,\"method\":\"logEvent\",\"params\":{\"name\":\"purchase\",\"params\":{\"value\":\"100\",\"currency\":\"USD\"}}}".getBytes(StandardCharsets.UTF_8);

        return new HttpRequest.Builder()
                .setUrl("code://com.google.firebase.analytics.FirebaseAnalytics")
                .setHttpMethod("POST")
                .setProvider("lib-firebase")
                .setRequestPayload(payloadBytes)
                .setRequestPayloadNumBytes(payloadBytes.length)
                .setInterceptionModule("firebase")
                .build();
    }

    private InterceptionContext createContext() {
        return InterceptionContext.createInterceptionContext(context);
    }
}
